swagger: '2.0'
info:
  title: Dex Analytics MCP Server
  description: MCP Server para Google Analytics e Search Console compatível com Copilot Studio
  version: 1.0.0
host: dex-mcp-server-1212.onrender.com
basePath: /api
schemes:
  - https
paths:
  /mcp:
    post:
      summary: Dex Analytics MCP Server
      x-ms-agentic-protocol: mcp-streamable-1.0
      operationId: InvokeMCP
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - name: body
          in: body
          required: true
          schema:
            type: object
            properties:
              jsonrpc:
                type: string
                default: "2.0"
              id:
                type: string
                default: "1"
              method:
                type: string
                enum: ["initialize", "tools/list", "tools/call"]
              params:
                type: object
      responses:
        '200':
          description: Success